### ISSUE TITLE
服务端docker启动失败  F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Program.cs:line 53

### ISSUE THREAD

**Issue by luxlzz6** [TerraMours/TerraMours_Admin_Web#16]
报错 $(String[] args) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Program.cs:line 53 这个呢

**Comment by raokun** [comment]
昨天服务端的docker镜像有更新，可以重新重装一下。还有问题的话，可以看看docker的容器中的日志。

**Comment by luxlzz6** [comment]
> 昨天服务端的docker镜像有更新，可以重新重装一下。还有问题的话，可以看看docker的容器中的日志。

报错这个

Sending HTTP request GET http://127.0.0.1:3116/health
[11:22:36 ERR] GetHealthReport threw an exception when trying to get report from http://127.0.0.1:3116/health configured with name Local.
System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:3116)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 122

**Comment by luxlzz6** [comment]
> > 昨天服务端的docker镜像有更新，可以重新重装一下。还有问题的话，可以看看docker的容器中的日志。
> 
> 报错这个
> 
> Sending HTTP request GET http://127.0.0.1:3116/health [11:22:36 ERR] GetHealthReport threw an exception when trying to get report from http://127.0.0.1:3116/health configured with name Local. System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:3116) ---> System.Net.Sockets.SocketException (111): Connection refused at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 122

volumes:
      # 图片挂载地址，将容器中的图片挂载出来
      - /data/TerraMours/images:/app/images
      # 可挂载自定义的配置文件快速进行系统配置
      # - /data/TerraMours/appsettings.json/appsettings.json:/app/appsettings.json
    ports:
      - "3117:80"
    restart: always
    
    这里端口改了也不行 还是提示GetHealthReport threw an exception when trying to get report from http://127.0.0.1:3116/health configured with name Local.
System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:3116) 好像是默认的3116

**Comment by raokun** [comment]
这个是健康检查，你可以删了镜像拉下最新的，或者把服务端的github上的appsettings.json文件拷到服务端，通过挂载修改容器中的配置文件
# 可挂载自定义的配置文件快速进行系统配置
 - /data/TerraMours/appsettings.json/appsettings.json:/app/appsettings.json
 
文件地址改成你服务器对应appsettings.json所在地址

**Comment by luxlzz6** [comment]
> 这个是健康检查，你可以删了镜像拉下最新的，或者把服务端的github上的appsettings.json文件拷到服务端，通过挂载修改容器中的配置文件
> # 可挂载自定义的配置文件快速进行系统配置
> 
>     * /data/TerraMours/appsettings.json/appsettings.json:/app/appsettings.json
> 
> 
> 文件地址改成你服务器对应appsettings.json所在地址

不报错了，但是管理系统登录不上，可以注册成功 登录不上 刷新后卡在
![图片](https://github.com/TerraMours/TerraMours_Admin_Web/assets/53847251/b87e3609-c56c-466c-8593-07d5f4cdd0bd)

**Comment by raokun** [comment]
> > 这个是健康检查，你可以删了镜像拉下最新的，或者把服务端的github上的appsettings.json文件拷到服务端，通过挂载修改容器中的配置文件
> > # 可挂载自定义的配置文件快速进行系统配置
> > ```
> > * /data/TerraMours/appsettings.json/appsettings.json:/app/appsettings.json
> > ```
> > 
> > 
> > 文件地址改成你服务器对应appsettings.json所在地址
> 
> 不报错了，但是管理系统登录不上，可以注册成功 登录不上 刷新后卡在 ![图片](https://user-images.githubusercontent.com/53847251/275404685-b87e3609-c56c-466c-8593-07d5f4cdd0bd.png)

需要看下服务端的容器的日志，看下什么问题导致的，或者你F12看下页面是什么原因报错的。（管理端目前只能管理员登陆）

**Comment by firstsaofan** [comment]
注册的账号只能前端服务登录，后台管理只能默认的管理员账号登录，或者你给了管理员权限才能登录。

**Comment by luxlzz6** [comment]
> 注册的账号只能前端服务登录，后台管理只能默认的管理员账号登录，或者你给了管理员权限才能登录。

"Initial": {
      "InitialRoleId": "2", //新增用户默认的角色id
      "InitialPassWord": "1a!23456" //新增用户默认的密码
    },
    是这里设置的嘛

**Comment by firstsaofan** [comment]
@raokun 默认的后台管理员账号应该是
账号：terramours@163.com
密码：terramours@163.com
对吗？

**Comment by raokun** [comment]
> > 注册的账号只能前端服务登录，后台管理只能默认的管理员账号登录，或者你给了管理员权限才能登录。
> 
> "Initial": { "InitialRoleId": "2", //新增用户默认的角色id "InitialPassWord": "1a!23456" //新增用户默认的密码 }, 是这里设置的嘛

是的，InitialRoleId设置成sysuser表里对应的管理员角色的id，新建的用户才能登陆admin

**Comment by raokun** [comment]
> @raokun 默认的后台管理员账号应该是 账号：[terramours@163.com](mailto:terramours@163.com) 密码：[terramours@163.com](mailto:terramours@163.com) 对吗？

是的

**Comment by luxlzz6** [comment]
可以使用本地的MySQL嘛

**Comment by firstsaofan** [comment]
用的EF Core 自己改造就行了。我们只提供pgsql。

**Comment by luxlzz6** [comment]
admin:
    image: raokun88/terramours_gpt_admin:latest
    container_name: terramoursgptadmin
    environment:
      - VUE_APP_API_BASE_URL=http://192.168.3.12:3116
      
  这几个地址不能设置成http://127.0.0.1:3116 呢 必须填内网IP 才能连上，
 使用内网IP又会有这个错误 Access to XMLHttpRequest at 'http://192.168.3.12:3116/api/v1/Category/GetAllCategoryList' from origin 'http://192.168.3.12:3226' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by raokun** [comment]
> admin: image: raokun88/terramours_gpt_admin:latest container_name: terramoursgptadmin environment: - VUE_APP_API_BASE_URL=http://192.168.3.12:3116
> 
> 这几个地址不能设置成http://127.0.0.1:3116 呢 必须填内网IP 才能连上， 使用内网IP又会有这个错误 Access to XMLHttpRequest at 'http://192.168.3.12:3116/api/v1/Category/GetAllCategoryList' from origin 'http://192.168.3.12:3226' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

VUE_APP_API_BASE_URL是前端调用后端服务的url，需要改成你的服务器的ip加后端服务的端口

**Comment by luxlzz6** [comment]
> > admin: image: raokun88/terramours_gpt_admin:latest container_name: terramoursgptadmin environment: - VUE_APP_API_BASE_URL=http://192.168.3.12:3116
> > 这几个地址不能设置成http://127.0.0.1:3116 呢 必须填内网IP 才能连上， 使用内网IP又会有这个错误 Access to XMLHttpRequest at 'http://192.168.3.12:3116/api/v1/Category/GetAllCategoryList' from origin 'http://192.168.3.12:3226' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> VUE_APP_API_BASE_URL是前端调用后端服务的url，需要改成你的服务器的ip加后端服务的端口

修改为服务器ip 有一些菜单会有这个跨域问题，比如商品和商品列表 编辑用户
 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by raokun** [comment]
前端是https的话，调用http接口会跨域。1.nginx转发后端apiurl成https。2.前端使用http

**Comment by luxlzz6** [comment]
现在全都都是在内网环境下测试

**Comment by luxlzz6** [comment]
> 前端是https的话，调用http接口会跨域。1.nginx转发后端apiurl成https。2.前端使用http

现在报错
 Start processing HTTP request GET http://192.168.3.12:3116/health
terramours_gpt_server  | [15:16:02 INF] Sending HTTP request GET http://192.168.3.12:3116/health
terramours_gpt_server  | [15:16:02 WRN] Failed to determine the https port for redirect.
terramours_gpt_server  | [15:16:02 ERR] HTTP GET /health responded 500 in 255.2737 ms
terramours_gpt_server  | System.NullReferenceException: Object reference not set to an instance of an object.
terramours_gpt_server  |    at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24
terramours_gpt_server  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
terramours_gpt_server  | [15:16:02 ERR] Connection id "0HMUES3LP47VK", Request id "0HMUES3LP47VK:00000001": An unhandled exception was thrown by the application.
terramours_gpt_server  | System.NullReferenceException: Object reference not set to an instance of an object.
terramours_gpt_server  |    at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24
terramours_gpt_server  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
terramours_gpt_server  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
检测一直500了

**Comment by raokun** [comment]
更新下后端服务镜像，最新的镜像修改了。如果是之前的，可以使用挂载appsettings.json的方式，注释掉配置文件中的自定义健康检查地址。
![image](https://github.com/TerraMours/TerraMours_Admin_Web/assets/43564692/cf044369-3fcc-4660-b520-1aa8f44a5597)

**Comment by luxlzz6** [comment]
> 更新下后端服务镜像，最新的镜像修改了。如果是之前的，可以使用挂载appsettings.json的方式，注释掉配置文件中的自定义健康检查地址。 ![image](https://user-images.githubusercontent.com/43564692/275748149-cf044369-3fcc-4660-b520-1aa8f44a5597.png)


登录提示 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.|
报错  HTTP OPTIONS /api/v1/Login/Login responded 204 in 1.6750 ms
terramours_gpt_server  | [15:41:28 ERR] HTTP POST /api/v1/Login/Login responded 500 in 2.6435 ms
terramours_gpt_server  | System.NullReferenceException: Object reference not set to an instance of an object.
terramours_gpt_server  |    at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24
terramours_gpt_server  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
terramours_gpt_server  | [15:41:28 ERR] Connection id "0HMUESHES82VJ", Request id "0HMUESHES82VJ:00000004": An unhandled exception was thrown by the application.
terramours_gpt_server  | System.NullReferenceException: Object reference not set to an instance of an object.
terramours_gpt_server  |    at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24
terramours_gpt_server  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
terramours_gpt_server  |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
terramours_gpt_server  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by raokun** [comment]
> > 更新下后端服务镜像，最新的镜像修改了。如果是之前的，可以使用挂载appsettings.json的方式，注释掉配置文件中的自定义健康检查地址。 ![image](https://user-images.githubusercontent.com/43564692/275748149-cf044369-3fcc-4660-b520-1aa8f44a5597.png)
> 
> 登录提示 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.| 报错 HTTP OPTIONS /api/v1/Login/Login responded 204 in 1.6750 ms terramours_gpt_server | [15:41:28 ERR] HTTP POST /api/v1/Login/Login responded 500 in 2.6435 ms terramours_gpt_server | System.NullReferenceException: Object reference not set to an instance of an object. terramours_gpt_server | at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24 terramours_gpt_server | at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) terramours_gpt_server | at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) terramours_gpt_server | at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext) terramours_gpt_server | [15:41:28 ERR] Connection id "0HMUESHES82VJ", Request id "0HMUESHES82VJ:00000004": An unhandled exception was thrown by the application. terramours_gpt_server | System.NullReferenceException: Object reference not set to an instance of an object. terramours_gpt_server | at TerraMours_Gpt.Framework.Infrastructure.Middlewares.KeyMiddleware.InvokeAsync(HttpContext context) in F:\个人\TerraMours_Gpt_Api\TerraMours\TerraMours\Framework\Infrastructure\Middlewares\KeyMiddleware.cs:line 24 terramours_gpt_server | at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) terramours_gpt_server | at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) terramours_gpt_server | at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext) terramours_gpt_server | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

https://terramours.site/guide/#_1-%E5%9F%BA%E4%BA%8Edockercompose%E7%9A%84%E5%BF%AB%E9%80%9F%E6%90%AD%E5%BB%BAai%E8%81%8A%E5%A4%A9%E5%92%8C%E7%94%BB%E5%9B%BE%E7%B3%BB%E7%BB%9F

官网的dockercompose更新了，对于提出的常见问题也写了注意事项。另外，添加了seq日志系统，系统的报错可以更快捷的查看。
